# KYC Agent Validation & Business Constants

# Score Weights (Must sum to 100)
WEIGHT_PERSONAL_INFO = 20.0
WEIGHT_ADDRESS = 20.0
WEIGHT_IDENTITY_DOCS = 20.0
WEIGHT_OCCUPATION = 10.0
WEIGHT_SOURCE_OF_FUNDS = 15.0
WEIGHT_SOURCE_OF_WEALTH = 10.0
WEIGHT_TAX_RESIDENCY = 5.0

# Rule Identifiers
RULE_MISSING_NAME = "KYC001"
RULE_MISSING_DOB = "KYC002"
RULE_MISSING_DOCS = "KYC003"
RULE_MISSING_ADDRESS = "KYC004"
RULE_MISSING_SOW = "KYC005"
RULE_MISSING_SOF = "KYC006"
RULE_MISSING_OCCUPATION = "KYC007"
RULE_MISSING_TAX_RESIDENCY = "KYC008"
RULE_MISSING_GENDER = "KYC009"
RULE_MISSING_NATIONALITY = "KYC010"

# KYC Statuses
STATUS_COMPLETE = "COMPLETE"
STATUS_INCOMPLETE = "INCOMPLETE"
STATUS_PENDING = "PENDING"
STATUS_FAILED = "FAILED"

# Risk Levels
RISK_LOW = "low"
RISK_MEDIUM = "medium"
RISK_HIGH = "high"
