apiVersion: v1
kind: Secret
metadata:
  name: aml-secrets
  namespace: aml-compliance
type: Opaque
data:
  SECRET_KEY: VmVyeVNlY3JldEpXVEtleUZvclRva2Vuc19SZXBsYWNlSW5Qcm9kdWN0aW9u
  ENCRYPTION_KEY: StrongAESKeyForPIIEncryptionBase64String=
  DATABASE_URL: cG9zdGdyZXNxbCthc3luY3BnOi8vY29tcGxpYW5jZV9hZG1pbjpTZWNyZXRTZWN1cmVQYXNzd29yZDk5QGFtbC1wb3N0Z3Jlcy1wcmltYXJ5LXN2Yzo1NDMyL2FtbF9jb21wbGlhbmNlX2Ri
  DATABASE_REPLICA_URL: cG9zdGdyZXNxbCthc3luY3BnOi8vY29tcGxpYW5jZV9hZG1pbjpTZWNyZXRTZWN1cmVQYXNzd29yZDk5QGFtbC1wb3N0Z3Jlcy1yZXBsaWNhLXN2Yzo1NDMyL2FtbF9jb21wbGlhbmNlX2Ri
  REDIS_URL: cmVkaXM6Ly9hbWwtcmVkaXMtbWFzdGVyLXN2Yzo2Mzc5LzA=
  REDIS_SENTINELS: YW1sLXJlZGlzLXNlbnRpbmVsLXN2YzoyNjM3OQ==
